version: '3'
services:
  dind:
    image: docker:dind
    privileged: true
  jenkins:
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  jenkinsnet:

